# Step 1: Define a ClusterIssuer or Issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: vikasedu10@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx

---
# Step 2: Create a Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crt-tls
spec:
  secretName: cert-tls-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - platform.vikasedu10.shop

# Step 3: Update Nginx Deployment (assuming you already have one)
# Add volumes and volume mounts for the SSL certificate
# Mount the secret containing the SSL certificate into your Nginx container

---
# Step 4: Define an Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - platform.vikasedu10.shop
    secretName: cert-tls-secret
  rules:
  - host: platform.vikasedu10.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
