apiVersion: apps/v1
kind: Deployment
metadata:
  name: cacplatformui
spec:
  replicas: 1 # Number of replicas you want to deploy
  selector:
    matchLabels:
      app: cacplatformui
  template:
    metadata:
      labels:
        app: cacplatformui
    spec:
      containers:
        - name: cacplatformui
          image: cacplatformui.azurecr.io/cacplatformui:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # Port that your React app is running on
          env:
            - name: REACT_APP_DNS_URL
              value: cacplatformui.com1
            - name: REACT_APP_NODE_ENV
              value: production
            - name: REACT_APP_PLATFORM_DNS_URL
              value: cacplatformapi.default.svc.cluster.local:9091/goengine
            - name: REACT_APP_KEYCLOAK_URL
              value: http://keycloak.default.svc.cluster.local:8080/auth
            - name: REACT_APP_KEYCLOAK_REALM_NAME
              value: keycloak-cac-platform
            - name: REACT_APP_KEYCLOAK_CLIENT_ID
              value: react-auth
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cacplatformui
spec:
  selector:
    app: cacplatformui
  ports:
    - name: http
      port: 8081 # Port that the service should listen on
      targetPort: 3000 # Port that the pods are listening on
  type: LoadBalancer # Use LoadBalancer type if running on cloud providers like AWS, GCP etc
