name: Build Test Push Platform UI image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build-Push-Platform-UI:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: self-hosted

    steps:
    - name: Checkout PlatformUI code
      uses: actions/checkout@v2

    - name: Install Docker
      run: |
        docker --version && sleep 1

    - name: Login to Github Container Repository
      run: |
        echo ${{ secrets.GH_PAT_TOKEN }} | docker login ghcr.io --username ${{ secrets.GH_REGISTRY_USER }} --password-stdin

    - name: Setup Git credentials
      run: |
        git config --global user.email "vikasedu10@gmail.com"
        git config --global user.name "Automation Bot"
        echo "Git config completed successfully!"

    - name: Install package.json
      run: npm install

    - name: Run Semantic-Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run semantic-release

    - name: Get Version from package.json
      id: package_version
      run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

    - name: Get Short Commit SHA
      id: git_sha
      run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

    - name: Build Docker image for React application
      run: |
        VERSION=${{ steps.package_version.outputs.version }}
        COMMIT_SHA=${{ steps.git_sha.outputs.sha }}
        TAG="v${VERSION}-${COMMIT_SHA}"
        echo "TAG=v${VERSION}-${COMMIT_SHA}" >> $GITHUB_ENV
        docker build -t ghcr.io/vikasedu10/platformui:${TAG} .
        echo "Image is build successfully with version ${TAG}!"
    
    - name: Push Docker image to GCR
      run: |
        docker push ghcr.io/vikasedu10/platformui:${TAG}
        echo "Image is pushed to Github CR successfully with version tag: ${TAG}!"

  Trigger-Infrastructure:
      needs: Build-Push-Platform-UI
      runs-on: self-hosted

      steps:
        - name: Trigger Infrastructure
          run: |
            curl -X POST \
                -H "Authorization: token ${{ secrets.GH_PAT_TOKEN }}" \
                -H "Accept: application/vnd.github.everest-preview+json" \
                "https://api.github.com/repos/vikasedu10/tf-aws-cluster/dispatches" \
                -d '{"event_type": "trigger-infrastructure"}'